### ISSUE TITLE
Cannot access table created by group member

### ISSUE THREAD

**Issue by s2barcla** [morrmarco/Ivey-Hack-The-Case#5]
Hi there,

One of my group members created a new table and uploaded it into our shared folder. We all moved this table to our own libraries to work on individually. However, when other members try to access the new table in the library, it says that we do not have the authorization for this library. Is there a way to change this?

Thank you!

**Comment by jstaf** [comment]
So when you create a file - it has read permissions for everyone in your group, but write permissions only to the owner of the file. 

To change the permissions so that everyone can write to the file, run the following command. You'll need to execute this in a terminal somewhere - both JupyterHub and RStudio have a nice terminal (alternatively, I can run this for you if you tell me which files to do it on):

```bash
chmod g+w /home/teams/yourteam/some_table.sas7bdat
```

Keep in mind the caveat that you don't want multiple people to be writing to the file at the same time - as subsequent changes will overwrite what was originally there.

**Comment by s2barcla** [comment]
Awesome thank you! We will run that code in RStudio.
